Update lesson
learn-co-curriculum/react-ts-forms-lab pull request #1
Opened 2022-09-16 19:38 UTC by jlboba

Changes made:
- Configured for TS 
- Added a general note about typing, otherwise left it mostly alone. Most big changes were done in the solution itself 

Solution branch available

2022-09-26 17:38 UTC, lizbur10 requested changes
When I pull down the solution branch, I see two typescript errors in VSCode:

<img width="672" alt="Screen Shot 2022-09-26 at 1 30 47 PM" src="https://user-images.githubusercontent.com/9666939/192343270-593a3b31-3e47-4f10-8d4c-c5424542fda1.png">
<img width="694" alt="Screen Shot 2022-09-26 at 1 31 16 PM" src="https://user-images.githubusercontent.com/9666939/192343298-16b46c37-cea9-4ee8-a286-a337e2de6088.png">

I can't figure out how to fix them, which is making me nuts...

2022-09-26 17:38 UTC, lizbur10 commented on README.md
> +
The tests are opinionated for the Filter component - in addition to needing a prop called `onSearchChange` as the callback for the search functionality (mentioned on lines 56-57), it also has to have a `search` prop that holds the search term. I recommend explaining this explicitly, perhaps as a note at the end of this section. (I might also remove the "**Note:**" from the existing note and make it a regular paragraph so there aren't two of them...)

There's a similar situation for the `ItemForm` component that's described on lines 90-92. I would handle this the same way with a more noticeable "Note" at the end of the section

2022-09-28 18:30 UTC, jlboba commented
@lizbur10 I can't seem to reproduce the errors you received in the solution branch. From the screenshots, I can't tell how to fix them either 😕 Do the errors still show up when npm installing and starting?

2023-04-10 15:59 UTC, AlveeM approved these changes

2023-04-10 15:59 UTC, merged